// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("AzureStorageSandbox")>]
[<assembly: AssemblyProductAttribute("AzureStorageSandbox")>]
[<assembly: AssemblyDescriptionAttribute("AzureStorageSandbox")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "AzureStorageSandbox"
    let [<Literal>] AssemblyProduct = "AzureStorageSandbox"
    let [<Literal>] AssemblyDescription = "AzureStorageSandbox"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
